### ISSUE TITLE
Incorrect method name reference in IllegalArgumentException message

### ISSUE THREAD

**Issue by margue** [camunda/camunda-bpm-assert#100]
The util methods for completing a Task throw IllegalArgumentExceptions for null Parameters with a message "Illegal call of claim (...)". Should be "Illegal call of complete (...)".

**Comment by zambrovski** [comment]
already fixed in https://github.com/holunda-io/camunda-bpm-assert version 2.1

**Comment by tmetzke** [comment]
Hi Martin,

thanks for spotting this.

We fixed this in the 3.0.0-alpha1 release as mentioned in the PR https://github.com/camunda/camunda-bpm-assert/pull/101.

Closing this as fixed.

Best,
Tobias
