### ISSUE TITLE
Missing docs for Sending Messages

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-bpm-assert#106]
The Toc for BPMN has:

https://github.com/camunda/camunda-bpm-assert/blob/master/camunda-bpm-assert/User_Guide_BPMN.md

Sending messages
Sending messages and passing process variables

But they cannot be found on the page.

**Comment by tmetzke** [comment]
Hey Stephen,

thanks for pointing this out!

I removed the entries from the TOC on master.
In case this is needed as a feature, please don't hesitate to open [an issue](https://app.camunda.com/jira/browse/CAM/component/14065) or PR.

Thanks again!

Best,
Tobias
