### ISSUE TITLE
Enable AssertThat to have the String Description argument rather than having to use describedAs

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-bpm-assert#108]
currently AssertThat does not support string descriptions of the assertion.  This is something that AssertJ supports, but it is not passed through into the Camunda asserts.

**Comment by tmetzke** [comment]
Hi Stephen,

thanks for opening this issue.
Could you clarify the behavior you would like to see in an example?
Could you share a link to where this feature is described in AssertJ (if applicable)?

Thank you!

Best,
Tobias

**Comment by tmetzke** [comment]
Closing this as not specified enough.
Please feel free to reopen with further details.
