### ISSUE TITLE
CAM-10022: Introduce a maven wrapper

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-assert#111]
I made very good experienes with using the https://github.com/takari/maven-wrapper

it allows configuring the maven version per project and runs it via wrapper (./mvnw).
This makes the build more reprducable since it does not rely on the locally installed maven version.

So lets use this here as well.

This would effect all ci-builds as well to fully use the potential.

**Comment by StephenOTT** [comment]
+1

**Comment by hawky-4s-** [comment]
Merge the change and assign me afterwards, I will update the ci

Stephen Russett <notifications@github.com> schrieb am So., 17. Juni 2018,
19:14:

**Comment by zambrovski** [comment]
Solved in https://github.com/holunda-io/camunda-bpm-assert

**Comment by tmetzke** [comment]
Hi Jan,

thanks for proposing this!

We will look into this as soon as possible and track the further progress in https://app.camunda.com/jira/browse/CAM-10022.

You are of course welcome to submit a pull request to speed up the integration of the feature.

I am closing this as transferred to JIRA.

Best,
Tobias
