### ISSUE TITLE
job(activity) HelperMehod not working when there are multiple jobs

### ISSUE THREAD

**Issue by stefanzilske** [camunda/camunda-bpm-assert#120]
I have a process waiting at an intermediate message catch event, while at the same time there is a timer event subprocess. When I call `BpmnAwareTests.job(activityIfOfTheMessageCatchEvent)` it throws "Query return 2 results instead of max 1" because the JobQuery in `ProcessInstanceAssert.java:630` finds both jobs, the message and the timer.

I think it would be better to call the JobQuery not with the executionId, but with the activityId.

**Comment by tmetzke** [comment]
Hi @stefanzilske,

thanks for raising this.
Please be aware that we are now tracking issues of this project in our [Issue Tracker](https://app.camunda.com/jira/browse/CAM/component/14065). 
I would kindly ask you to open a ticket there next time.
I created the corresponding issue [CAM-10848](https://app.camunda.com/jira/browse/CAM-10848) there.

Concerning the current issue, could you provide a minimal failing example?
Please have a look at the attached model and the test [in the issue](https://app.camunda.com/jira/browse/CAM-10848), which works absolutely fine.

Best,
Tobias
