### ISSUE TITLE
Tanslate bpmn files to english

### ISSUE THREAD

**Issue by anborg** [camunda/camunda-bpm-assert#128]
I translated from german to english, and made code modification, need to checkin

![image](https://user-images.githubusercontent.com/56970398/73140149-941aeb00-4043-11ea-8975-e579fdbde979.png)

![image](https://user-images.githubusercontent.com/56970398/73140153-9bda8f80-4043-11ea-80db-1284fb27caea.png)

**Comment by ThorbenLindhauer** [comment]
Please ask the camunda user forum: https://forum.camunda.org/
