### ISSUE TITLE
Typo in the assertion error message

### ISSUE THREAD

**Issue by fml2** [camunda/camunda-bpm-assert#142]
In https://github.com/camunda/camunda-bpm-assert/blob/master/core/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/ProcessInstanceAssert.java, there is the message `...but actually we instead we found that it passed...`. "We" occurs twice. Better wording would be IMO "...but it actually passed...". No need to bring "we" in.

**Comment by tmetzke** [comment]
Hey @fml2,

thanks for the hint, I fixed it.

I'd encourage you to open a PR or a ticket in our [issue tracker](https://jira.camunda.com/projects/CAM) for such things next time, as we are not looking into issues here regularly anymore, see our [Contribution Guide](https://github.com/camunda/camunda-bpm-assert/blob/master/CONTRIBUTING.md).

Best,
Tobias
