### ISSUE TITLE
Why did you remove the UserGuide?

### ISSUE THREAD

**Issue by kper** [camunda/camunda-bpm-assert#160]
Before merging `camunda-bpm-assert` into Camunda, it had a nice user guide. Why was this removed? 

https://github.com/camunda/camunda-bpm-assert/blob/a1d0d0411b8b2bc2dd9f669c948ec5f5fe09f671/docs/User_Guide_BPMN.md

**Comment by ThorbenLindhauer** [comment]
Hi, you can find this as part of the official documentation now: https://docs.camunda.org/manual/7.17/user-guide/testing/assert-examples/

Cheers!
