### ISSUE TITLE
Update default camunda version to 7.2.0

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#38]

**Comment by zambrovski** [comment]
See Issue #39 of why we should go to 7.2

**Comment by martinschimak** [comment]
I think I prefer to implement as much assertions as possible with the minimum version necessary to get the particular job done. Therefore, I propose to use Camunda BPM FormService for #39.

**Comment by martinschimak** [comment]
Implicitely resolved by #56. We compile now always with the current release (currently 7.4.0), but test against all releases.
