### ISSUE TITLE
Add assertions for CMMN Case Instances

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-assert#40]

**Comment by malteser** [comment]
Any news on this? I'm at the point where this would be a great help.

**Comment by martinschimak** [comment]
Hi @malteser  - no further news yet on this. As you are at a point where this would be a great help - any insights about what exactly you would need or how your cmmn use cases or your test code so far looks like would be very helpful!

**Comment by malteser** [comment]
Hi @martinschimak, I've started writing my own asserts, but unfortunately I'm not allowed to share my code.

What I use most often are assertions for checking that certain tasks and stages are in a specific state.
E.g. `assertThat(caseInstance).task("foobar").isEnabled()`
Or for multiple tasks `assertThat(caseInstance).stage("foo").hasEnabledTasks("a", "b")`

Hope that helps,
Malte

**Comment by martinschimak** [comment]
Hi @berndruecker - because you reported this first: we made quite some progress in this arena, so in case you somewhere find half an hour to have a look at the current cmmn_assertions branch here, you are welcome, of course. If not, also fine, I am currently quite happy about the direction... so then we would just move on without your feedback... :smile:

**Comment by berndruecker** [comment]
Not yet sure if I find the time – but I will try (I would have some examples/showcases where I could add some tests :-))

Von: Martin Schimak [mailto:notifications@github.com]
Gesendet: Donnerstag, 26. November 2015 13:45
An: camunda/camunda-bpm-assert <camunda-bpm-assert@noreply.github.com>
Cc: Bernd Rücker <bernd.ruecker@camunda.com>
Betreff: Re: [camunda-bpm-assert] add assertions for CMMN / case instances (#40)


Hi @berndruecker<https://github.com/berndruecker> - because you reported this first: we made quite some progress in this arena, so in case you somewhere find half an hour to have a look at the current cmmn_assertions branch here, you are welcome, of course. If not, also fine, I am currently quite happy about the direction... so then we would just move on without your feedback... [:smile:]

**Comment by martinschimak** [comment]
But hey, in case you can share some executable examples/showcases publicly :eyes: , please just add them to the resources folder in the new cmmn-examples module, even if you don't have time to add any tests! Would be very helpful for further assertions development and illustration!

**Comment by berndruecker** [comment]
I think the showcase with the most CMMN inside is here: https://github.com/camunda/camunda-consulting/tree/master/showcases/underwriting


Von: Martin Schimak [mailto:notifications@github.com]
Gesendet: Donnerstag, 26. November 2015 18:16
An: camunda/camunda-bpm-assert <camunda-bpm-assert@noreply.github.com>
Cc: Bernd Rücker <bernd.ruecker@camunda.com>
Betreff: Re: [camunda-bpm-assert] add assertions for CMMN / case instances (#40)


But hey, in case you can share some executable examples/showcases publicly [:eyes:] , please just add them to the resources folder in the new cmmn-examples module, even if you don't have time to add any tests! Would be very helpful for further assertions development and illustration!

**Comment by malteser** [comment]
Underwriting? That rings a bell ;)

**Comment by tmetzke** [comment]
CMMN Case Instance Assertions have been officially added with 3.0.0-alpha1.
Feel free to check it out!

Closing this as fixed.

Best,
Tobias
