### ISSUE TITLE
CAM-10030: isWaitingFor() ... support the check for a specific correlation expectation

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#49]
Currently the isWaitingFor/isNotWaitingFor assertions just support the message name. It would be meaningful to also support a check for the existence of specifically expected correlation keys (business keys, process instance variables)

**Comment by tmetzke** [comment]
We will track the further progress of this in https://app.camunda.com/jira/browse/CAM-10030.

I am closing this as transferred to JIRA.

Best,
Tobias
