### ISSUE TITLE
CAM-10028: Process Definition Assertions: is(Not)WaitingFor and is(Not)SubscribedFor

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#51]
Similar as for running process instances and their intermediate (message and signal) events, it should be possible to check whether process definitions wait for messages or subscribe to signals in order to create instances at start events.

**Comment by tmetzke** [comment]
We will track the further progress of this in https://app.camunda.com/jira/browse/CAM-10028.

I am closing this as transferred to JIRA.

Best,
Tobias
