### ISSUE TITLE
CAM-10027: new assertion assertThat(processInstance).hasBusinessKey(...)

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-assert#55]
strangly that one is missing ... though the business key is accessible via get() on the process instance.

**Comment by tmetzke** [comment]
Hey Jan,

it has been a while already, but thanks for proposing this.
We consider this to be a useful addition and will look into this as soon as possible.

Meanwhile, we will track the further progress in https://app.camunda.com/jira/browse/CAM-10027.
You are of course welcome to submit a pull request to speed up the integration of the feature.

I am closing this as transferred to JIRA.

Best,
Tobias
