### ISSUE TITLE
Improve Guidelines for Contributing

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#59]
As a new contributor, I need to know all design decisions + reasoning, in order to provide good contribututions.

**Comment by martinschimak** [comment]
I more than agree! Sorry that some of your effort so far was probably frustrated because of the lack of such guidelines. I guess we should complete this issue after having released a 2.0 with CMMN assertions, because we will then be fully aware of the guidelines and patterns we actually see.

**Comment by malteser** [comment]
I would like to add some stuff to the md and create a new ticket for refining it after the 2.0 release. 
Stuff would be 
1. create a ticket
1. small piece of work
1. make fork + branch
1. implement, document in md, document in javadoc, test systematically 
1. create pull request

addition for CMMN:
1. before making pul lrequest, mark implemented feature in cmmn.md

**Comment by martinschimak** [comment]
Sure! When improving the CONTRIBUTING.md you could also delete the placeholder stuff there. The file was actually never properly edited so far...

**Comment by malteser** [comment]
Hm, can't assign this issue to me. :disappointed:

**Comment by martinschimak** [comment]
I fear I can't change that quickly, because I am not an owner of that repository either. I will look into that with Camunda staff and come back to you.

**Comment by malteser** [comment]
Maybe it's ok that way. In the end, assigning is meant for keeping track on who's working on what. We could as well make a "mine!" comment in an issue.

**Comment by malteser** [comment]
Done. See https://github.com/camunda/camunda-bpm-assert/pull/61
