### ISSUE TITLE
Split the README.md into BPMN and CMMN parts

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#62]
Due to the size of the current README.md, we should not add the CMMN stuff to it.

Proposal:
/camunda-bpm-assert/README.md contains genric things and links to 
/camunda-bpm-assert/README-BPMN.md and
/camunda-bpm-assert/README-CMMN.md

Also, the README-CMMN.md should incorporate and replace CMMN.md.

**Comment by malteser** [comment]
2nd thought: User_Guide_BPMN.md and User_Guide_CMMN.md seem to be better names ;)

**Comment by martinschimak** [comment]
Agreed with respect to User Guide! I propose to leave CMMN.md as a more implementation relevant artefact only. If you prefer, you could e.g. rename it to Implementation_CMMN or Coverage_CMMN etc.

**Comment by malteser** [comment]
Done. See PR #63
