### ISSUE TITLE
CAM-10026: improve assertion error for execute(job(activityId))

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-assert#65]
I use

```
  execute(job(activityId))
```

when the process instance is not waiting at activityId, I get a meaningless message stating that something is null that schould not be null. I'd prefer to get the info that there is no job waiting at activityId ... especially when I have more then one async service or timer in my process.

**Comment by tmetzke** [comment]
Hey Jan,

it has been a while already, but thanks for spotting and proposing this.
A useful message would be a nice improvement in this case, agreed.

We will look into this as soon as possible and track the further progress in https://app.camunda.com/jira/browse/CAM-10026.
You are of course welcome to submit a pull request to speed up the integration of the feature.

I am closing this as transferred to JIRA.

Best,
Tobias
