### ISSUE TITLE
[CMMN] Support calledProcessInstance() for ProcessTasks

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#69]
should return a ProcessInstanceAssert for the ProcessInstance created by that ProcessTask.

**Comment by tmetzke** [comment]
Hi @malteser,

we consider this a useful extension, but we will not work on CMMN features any time soon.
We encourage you to make a code contribution by submitting a pull request.

Thank you for your understanding.

Best,
Tobias
