### ISSUE TITLE
[CMMN] MilestoneAssert.hasOccured?

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#73]
Hi all,

the `Coverage_CMMN.md` states that the MilestoneAssert should have a `hasOccured` method.

@martinschimak  I might remember this wrong: Do we have a "stay close to the camunda API" principle? If so, we should remove this method, shouldn't we?

**Comment by martinschimak** [comment]
Hi @malteser - don't have spare time to dig into this deeper at the moment - can you elaborate your thoughts a bit for me? Thank you!

**Comment by tmetzke** [comment]
Hi,

since this is not present in the documentation and code (anymore), I am closing this as fixed.

Best,
Tobias
