### ISSUE TITLE
[CMMN] Test and document StageAssert

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#82]

**Comment by berndruecker** [comment]
See also https://github.com/camunda/camunda-bpm-assert/issues/87

**Comment by tmetzke** [comment]
Tests (9964905bfc2b7dedfb20b733f1a25afdabfe4194) and documentation (dea3999393595bd4cfb4f0efd36ad05501eda101) have been added for stages.

Closing this as fixed.

Best,
Tobias
