### ISSUE TITLE
[CMMN] Completing caseExecutions and passing process variables

### ISSUE THREAD

**Issue by margue** [camunda/camunda-bpm-assert#84]
I would like to add the following feature(s): Like in the BPMNAwareTests class, it would be very useful to have a helper method
```java
public static Map<String, Object> withVariables(final String key, final Object value, final Object... furtherKeyValuePairs)
```
to use it with a new status changer method
```java
public static void complete(CaseExecution caseExecution, Map<String, Object> variables)
```
Any objections against adding these two methods?

**Comment by malteser** [comment]
merged plz close
(PR is #85)
