### ISSUE TITLE
[CMMN] add variable assertions support CaseTaskAssert

### ISSUE THREAD

**Issue by margue** [camunda/camunda-bpm-assert#86]
Add **feature** variable assertions to CaseTaskAssert.

This means, make methods
- variables()
- hasVariables(String... names)
- hasNoVariables()

public for CaseTaskAssert and provide test cases and documentation.

**Comment by margue** [comment]
I added these changes to the PR #83, so that I could resolve all merge conflicts beforehand. New commits belonging to this issue can be identified by the issue number in the commit message.

**Comment by tmetzke** [comment]
Closing this as merged.
Feel free to reopen in case something I didn't notice is still missing.

Best,
Tobias
