### ISSUE TITLE
[CMMN] TaskAssert - should it be really limited to current scope?

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-assert#88]
This maybe needs discussion.

Due to https://github.com/camunda/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java#L249 you currently need to do the taskAssert on the right "level", meaning the overall case or the respective case.

I wonder if you should be able to do taskAsserts on the CaseInstance level finding ALL Tasks of this Case Instance on arbitrary stages.

Oppinions?

**Comment by martinschimak** [comment]
Hi Bernd. I assume this is a duplicate of #72 - can you confirm that and agree with my question/opinion expressed overthere?

**Comment by berndruecker** [comment]
You are right - duplicate. Thanks.
