### ISSUE TITLE
[CMMN] Add caseExecution() and "LastAsserts" list

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-assert#89]
allow to read latest asserted caseExecution easly (compare to task() method https://github.com/camunda/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/bpmn/BpmnAwareTests.java#L207)

**Comment by tmetzke** [comment]
Hi,

we consider this a useful extension, but we will not work on CMMN features any time soon.
We encourage anyone to make a code contribution by submitting a pull request for this.

Thank you for your understanding.

Best,
Tobias
