### ISSUE TITLE
Merge branch CMMN assertions into master

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#91]
Hi all.

I want to inform you about a few developments. Next week I will have a focused 15 minutes opportunity to speak about community extensions at the Camunda BPM community day in Berlin, actually scheduled right after @jangalinski and @zambrovski. 👍 Looking forward! 😄 

On one hand I will quickly introduce the new "baby" of mine which was born as a branch here (I already mentioned that in my last skype conf with @malteser and @margue), but now already moved into its own github repository: https://github.com/camunda/camunda-bpm-assert-scenario. To give you a very quick heads up here: with a "scenario" it becomes possible to define "behaviour" for process waitstates upfront, then yell "go" and verify your expecations about what happened in the process engine "after the fact". In other words: "scenario" test cases strictly follow a given/when/then pattern for testing and render it obsolete to "drive" the process in an "imperative" manner. Necessary test case specific "waitstate" (activity) behaviour is "mocked/stubbed" in advance and called/executed on the way - just as e.g. service calls already are today. 

(There is bit more to it, because "scenarios" are able to deal with several process instances and call activities and "fast forward" them in a timewise "realistic" manner that was not doable so far within single threaded, fully controllable unit tests. Just saying to keep you interested 😄)

**Very important** in this context here: will this new project render the mature Camunda BPM Assert obsolete sooner or later? I am sure it won't! On one hand, many people will prefer to stick with the more traditional, imperative approach to process testing: drive the process forward a bit and assert the state. But on the other hand, Camunda BPM Assert assertions also become even more important for "scenario" based more "declarative" process testing, too. Because with "scenario" you cannot just stub "waitstate" (activity) behaviour in advance, but you can also define assertions for these points in advance -  to assert runtime state whenever a specified activity/waitstate is reached. Therefore "Scenario" and "Assert" usage will typically go hand in hand, even though there are no code dependencies to each other.

Therefore I will also speak about Camunda BPM Assert next week. And will say "thank you" to Holisticon for everything that happened here so far. I also want to use the opportunity to **now** merge the cmmn_assertions branch here into master - to make the recent work more visible and make a "statement" that there won't be another release without CMMN anymore. My personal goal and commitment is to release the 2.0 "Final" version of Camunda BPM Assert with full CMMN support by the end of 2016 (latest) and I very much hope that you will continue to support me!

I include @berndruecker from Camunda because he always was and is a great community supporter in general and a supporter for Camunda BPM Assert in particular.

Many thanks and looking forward to an interesting week!
Martin.

**Comment by jangalinski** [comment]
Wow ... that is a lot (and great) news ... looking forward to having a beer or two next week.

**Comment by martinschimak** [comment]
@jangalinski Looking forward, too! I am also working on a new readme (see https://github.com/camunda/camunda-bpm-assert/tree/doc/readme). Would you like me to add the holisticon logo in the footer area?

**Comment by jangalinski** [comment]
sure, always a good idea to do some advertsing ... 

    <img src="https://www.holisticon.de/wp-content/uploads/2013/05/holisticon-logo-hamburg.gif" align="right" />
