### ISSUE TITLE
If process is not ended, show where it waits

### ISSUE THREAD

**Issue by falko** [camunda/camunda-bpm-assert#93]
`assertThat(processInstance).isEnded();` throws the following error if the process is not ended:

```
java.lang.AssertionError: Expecting actual ProcessInstance {id='6', processDefinitionId='InformationCheckProcess:1:3', businessKey='23'} to be ended, but it is not!. (Please make sure you have set the history service of the engine to at least 'activity' or a higher level before making use of this assertion!)
```

Would it be possible to include the task where the process is waiting in the error message?

**Comment by tmetzke** [comment]
Hi Falko,

it has been a while already, but thanks for proposing this.
We consider this to be a useful addition and will look into this as soon as possible.
Meanwhile, we will be tracking further progress in https://app.camunda.com/jira/browse/CAM-10024.

Closing this as transferred to JIRA.

Best,
Tobias
