### ISSUE TITLE
Improve log assertion failed

### ISSUE THREAD

**Issue by lldata** [camunda/camunda-bpm-assert#94]
When using eclipse, and I have a flow that fails on an assertion, I only get the assertionerror in the JUnit view by default. Since eclipse's JUnit view is notorious for being hard to read (due to linewraps and scrollbars), It would be much preferable if this could somehow be improved.

Suggestions:
1) Log the AssertionError to the console
2) Use JUnit assertEquals instead. That will generate an exception, that eclipse can present in a popup.

In IntelliJ the AssertionError is logged, so it is not a big issue there.

**Comment by martinschimak** [comment]
As I am an IntelliJ user let me clarify this: you are saying that Eclipse does not honor the "AssertionError" as an exception of a type that is presented to the IDE user as a "failed" test?

**Comment by tmetzke** [comment]
Hi Lasse,

since there hasn't been any progress on this for a long time, I am closing this as stale.
Feel free to reopen if the issue still exists for you.

Best,
Tobias
