### ISSUE TITLE
cmmn_assertions branch broken since camunda 7.6

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#95]
Even though travis says everything's ok, the branch does not work with camunda versions >= 7.6.0.

**Steps to Reproduce:**

1. checkout branch
2. fix camunda-bpm-assert/pom.xml - dependencyManagement to use ${camunda-bpm.version} instead of RELEASE (see attached [patch.txt](https://github.com/camunda/camunda-bpm-assert/files/899862/patch.txt))
2. run ` mvn clean install -Dcamunda-bpm.version=7.6.0`

To make sure that 7.5.0 is fine run:
` mvn clean install -Dcamunda-bpm.version=7.5.0`

**Travis CI**

When looking at the travis logs for builds against RELEASE, e.g. https://travis-ci.org/camunda/camunda-bpm-assert/jobs/129415357
then it can be seen that 7.5.0 is used instead of the latest release:
`Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/camunda/bpm/dmn/camunda-engine-dmn-bom/7.5.0-SNAPSHOT/maven-metadata.xml`

The cause seems to be that maven is not able to download Information about the available releases as this line indicates:
`[WARNING] Could not transfer metadata org.camunda.bpm:camunda-bom/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: unknown error`

**Comment by stefanzilske** [comment]
See PullRequest: https://github.com/camunda/camunda-bpm-assert/pull/96

(fixes 7.6 but breaks versions < 7.6, due to incompatible changes in CMMN 1.1)

**Comment by martinschimak** [comment]
See my comment on #96
