### ISSUE TITLE
troubles using camunda-bpm-assert via bom from gradle

### ISSUE THREAD

**Issue by KlausUnger-SoftwareCraftsmen** [camunda/camunda-bpm-assert#97]
Hello,

I tried to setup a gradle-based camunda project using the SpringBoot Starter BOM. I'm using the Spring Gradle DependencyManagement plugin. When I add camunda-bpm BOM, I run into troubles resolving it.

> * What went wrong:
Could not resolve all dependencies for configuration ':testCompileClasspath'.
> Could not resolve org.camunda.bpm.extension:camunda-bpm-assert:2.0-alpha1.
  Required by:
      project : > org.camunda.bpm.extension.springboot:camunda-bpm-spring-boot-starter-test:2.0.0
   > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert:2.0-alpha1.
      > Could not parse POM https://repo1.maven.org/maven2/org/camunda/bpm/extension/camunda-bpm-assert/2.0-alpha1/camunda-bpm-assert-2.0-alpha1.pom
         > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://repo1.maven.org/maven2/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://jcenter.bintray.com/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
   > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert:2.0-alpha1.
      > Could not parse POM https://jcenter.bintray.com/org/camunda/bpm/extension/camunda-bpm-assert/2.0-alpha1/camunda-bpm-assert-2.0-alpha1.pom
         > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://repo1.maven.org/maven2/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://jcenter.bintray.com/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
   > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert:2.0-alpha1.
      > Could not parse POM https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/camunda-bpm-assert/2.0-alpha1/camunda-bpm-assert-2.0-alpha1.pom
         > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://repo1.maven.org/maven2/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://jcenter.bintray.com/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.
            > Could not resolve org.camunda.bpm.extension:camunda-bpm-assert-root:2.0-alpha1.
               > Could not parse POM https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom
                  > Could not find org.camunda.bpm:camunda-bom:RELEASE.

running the same build in maven works like a charm.

As far as I understand, from the gradle build, the property `<camunda-bpm.version>RELEASE</camunda-bpm.version>` is not set/recognised. 

See https://app.camunda.com/nexus/content/groups/public/org/camunda/bpm/extension/camunda-bpm-assert-root/2.0-alpha1/camunda-bpm-assert-root-2.0-alpha1.pom

Thanks in advance for any hints and pointers into the right direction!

**Comment by KlausUnger-SoftwareCraftsmen** [comment]
Here the mentioned maven and gradle build files. Please rename accordingly - due to upload restrictions!

[build.gradle.txt](https://github.com/camunda/camunda-bpm-assert/files/915975/build.gradle.txt)
[pom.xml.txt](https://github.com/camunda/camunda-bpm-assert/files/915976/pom.xml.txt)

**Comment by felix-mueller** [comment]
+1

**Comment by stefanzilske** [comment]
I had the same issues. Gradle seems to be unable to resolve `RELEASE`, as this is Maven specific.

For the moment, I think there is no other way than to use camunda-bpm-assert 1.2 instead of 2.0-alpha1, which should not be an issue, as long as you don't want to test CMMN cases, since that is the major new feature in 2.0-alpha1.

_If_ you want to test CMMN cases, 2.0-alpha1 will probably not help you anyway, as it is not compatible with Camunda 7.6.x at the moment. 

Checkout my pull request: https://github.com/camunda/camunda-bpm-assert/pull/96 and leave your :thumbsup: if you want to see CMMN assertions being compatible with 7.6.

**Comment by KlausUnger-SoftwareCraftsmen** [comment]
specifying explicitly the version 1.2 solved the broken build problem for now.

> ext {
    camundaAssertVersion = '1.2'
}
dependencies {
    // ...
    testCompile("org.camunda.bpm.extension:camunda-bpm-assert:${camundaAssertVersion}")
}

Thanks for the fast reply.

Nevertheless - it would be nice, if the BOM could be used from gradle straight forward upon release of 2.0.0!

**Comment by martinschimak** [comment]
Hi all. Agreed - I believe the usage of RELEASE was deprecated already some time ago. So it's kind of fair that gradle does not support it all. :-) So yes, let's use just specific versions asap and when #96 is merged we can release an 2.x-alpha2 version. Having said that... 2.x does not bring a lot more with regards to BPMN testing so far - so I assume 1.2 will work just fine for @KlausUnger-SoftwareCraftsmen - greetings btw! 😄

**Comment by KlausUnger-SoftwareCraftsmen** [comment]
@martinschimak - thanks for the feedback. Interested in meeting in real to discuss some topics?

Btw ... should I open another ticket for wanted version upgrades (e.g. assertj 1.7.1 => 3.6.1, which would be a breaking change)

**Comment by jangalinski** [comment]
the assertj version was a big topic when moving to spring-boot 1.5.x because they internally changed from 2.5 to 2.6 and are no longer compatible.  I would love to see an issue for this ... but since this requires Java8 I am not sure how we will deal with this in this extension ... maybe we should support a dedicated "camunda-bpm-assert-jdk8" module ...

**Comment by martinschimak** [comment]
The cmmn_assertions branch is not using the RELEASE version anymore, instead the explicit 7.6.0 version. I tested the 2.0-SNAPSHOT snapshot against a local gradle build. "Works for me" - but in order not to fall into the equally named trap, I'd appreciate a validation of some of the people reporting this before we release the 2.0-alpha2. Many thx.

**Comment by KlausUnger-SoftwareCraftsmen** [comment]
I was able to build my sample project (see gradle build enclosed above) without the need to specify the bom version explicitly. From my point of view I consider it fixed.

**Comment by martinschimak** [comment]
Many thx @KlausUnger-SoftwareCraftsmen
