### ISSUE TITLE
Release master branch as 2.0-alpha2

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#98]
branch: master
release version: 2.0-alpha2
next snapshot: 2.0-SNAPSHOT

**Comment by martinschimak** [comment]
@berndruecker as soon as #97 is verified I'd like to release. My question is: who can actually currently trigger this? Is it on "your" Jenkins? If yes, is it still as easy as it was to release a branch != master?

**Comment by martinschimak** [comment]
#97 is verified - we will release the branch as 2.0-alpha2 asap

**Comment by berndruecker** [comment]
@martinschimak Yes, I can trigger releases easily. So releasing an alpha2 it the job to do?

**Comment by martinschimak** [comment]
Yes. Please make sure to release the branch cmmn_assertions as stated above. Thank you @berndruecker!

**Comment by berndruecker** [comment]
Hi martin. I do not have any job in place to release a branch, so that would involve some more work. Could you merge that into the master and then we release alpha2? Actually in other places we do not release alphas based on branches either, so I think this is more consistent - or where do you see the problem?

**Comment by martinschimak** [comment]
I merged the branch into master and preserved the other one as 1.x. As I do see so many 👍 above 😄 let me add, why I did not so far. It's not related to your work, guys. It's more related to restructure the project a bit so that it becomes even easier to deal with the dependency matrix like JDK 6/7/8 and the Camunda versions - which are not always always fully backwards compatible. However, I wanted to merge the branch into master anyway a long time ago and opened #91 - but except of @jangalinski I did not get feedback back then. So I guess I was a bit undermotivated as a result. 😄

**Comment by martinschimak** [comment]
@berndruecker You could now release master as 2.0-alpha2

**Comment by jangalinski** [comment]
If we release from the (now merged) master, shouldn't we just call the release 2.0?

**Comment by berndruecker** [comment]
relessed 2.0-alpha2

**Comment by martinschimak** [comment]
@jangalinski We are probably not far away. I am not completely sure about the status of the CMMN assertions. At least one "test" issue still seems to be open... maybe somebody of you should comment on it? The issue #87 is open, too. Furthermore, I would assume that almost nobody used the CMMN assertions so far? It is my understanding that @stefanzilske will use them in a real life project now and report on that. I am looking forward to his feedback.

**Comment by stefanzilske** [comment]
@martinschimak you are right! In fact, I ugpraded to 2.0-alpha2 right away, to properly test my case (and to sleep better from now on :))

My case is rather simple at the moment, mainly using process tasks (no stages, no events etc.), so I am probably using only parts of the available features from `CmmnAwareTests`. What I used so far:

* Assertions of CaseInstance and CaseExecution state (enabled/active) depending on their manual activation and repition rules
* Access to process engine services (Case-, HistoryService aso) via `CmmnAwareTests`
* CaseExecutionQuery via `CmmnAwareTests`

So far it works like a charm. My case(s) will probably grow throughout the project, so I will be using mre features later on, but I would appreciate to switch to a non-alpha release at some point in time ;)

**Comment by martinschimak** [comment]
Great to get some first feedback, thank you @stefanzilske! Promised: we will release it at some point in time so that you can switch 😉! Just one small remark: I would actually recommend to stick to the ProcessEngineTests entry point - I still consider to remove those other entry points for a final release...

**Comment by stefanzilske** [comment]
Hi @martinschimak 

any news on the planned 2.0 final release?
